- id: gitleaks-protect
  name: Detect hardcoded secrets
  description: Detect hardcoded secrets using Gitleaks
  entry: gitleaks protect --redact --staged --source . -v --report-path report-gitleaks.json
  language: golang
  pass_filenames: false
- id: gitleaks-detect
  name: Detect hardcoded secrets
  description: Detect hardcoded secrets using Gitleaks
  entry: gitleaks detect --source . -v --report-path report-gitleaks.json
  language: golang
  pass_filenames: false
- id: gitleaks-docker
  name: Detect hardcoded secrets
  description: Detect hardcoded secrets using Gitleaks
  entry: zricethezav/gitleaks protect --verbose --redact --staged
  language: docker_image
